/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/check-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check User Exists */
        post: operations["kitchenapi_views_check_user_exists"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["kitchenapi_views_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["kitchenapi_views_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Menu Items */
        get: operations["kitchenapi_views_list_menu_items"];
        put?: never;
        /** Create Menu Item */
        post: operations["kitchenapi_views_create_menu_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Menu Item */
        get: operations["kitchenapi_views_get_menu_item"];
        /** Update Menu Item */
        put: operations["kitchenapi_views_update_menu_item"];
        post?: never;
        /** Delete Menu Item */
        delete: operations["kitchenapi_views_delete_menu_item"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tables */
        get: operations["kitchenapi_views_list_tables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/{table_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Table */
        get: operations["kitchenapi_views_get_table"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["kitchenapi_views_list_orders"];
        put?: never;
        /** Create Order */
        post: operations["kitchenapi_views_create_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["kitchenapi_views_get_order"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Order Status */
        patch: operations["kitchenapi_views_update_order_status"];
        trace?: never;
    };
    "/api/v1/kitchen/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kitchen Login
         * @description Login for kitchen staff only
         */
        post: operations["kitchenapi_views_kitchen_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kitchen/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kitchen Orders
         * @description Get all active orders for kitchen dashboard
         */
        get: operations["kitchenapi_views_get_kitchen_orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kitchen/orders/{order_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Order Status
         * @description Update order status
         */
        put: operations["kitchenapi_views_update_order_status"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kitchen/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kitchen Dashboard */
        get: operations["kitchenapi_views_kitchen_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["kitchenapi_views_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cart
         * @description Get cart data from Redis. Returns null if last_updated matches (no changes).
         */
        get: operations["kitchenapi_views_get_cart"];
        put?: never;
        /**
         * Sync Cart
         * @description Sync cart data to Redis with 1 hour expiry
         */
        post: operations["kitchenapi_views_sync_cart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Checkout
         * @description Start checkout process - locks the cart for all devices
         */
        post: operations["kitchenapi_views_start_checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Checkout Status
         * @description Get checkout status for a user
         */
        get: operations["kitchenapi_views_get_checkout_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Checkout Heartbeat
         * @description Keep checkout lock alive - call every 15 seconds from active checkout device
         */
        post: operations["kitchenapi_views_checkout_heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Checkout
         * @description Cancel checkout process
         */
        post: operations["kitchenapi_views_cancel_checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Checkout
         * @description Complete checkout - create order from cart and clear cart
         */
        post: operations["kitchenapi_views_complete_checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** UserExistsSchema */
        UserExistsSchema: {
            /** Exists */
            exists: boolean;
        };
        /** AuthResponseSchema */
        AuthResponseSchema: {
            /** Token */
            token: string;
            /** User */
            user: {
                [key: string]: unknown;
            };
        };
        /** ErrorSchema */
        ErrorSchema: {
            /** Error */
            error: string;
        };
        /** UserSchema */
        UserSchema: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginSchema */
        LoginSchema: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MenuItemSchema */
        MenuItemSchema: {
            /** Id */
            id?: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Price */
            price: number;
            /** Category */
            category: string;
            /**
             * Is Available
             * @default true
             */
            is_available: boolean;
            /** Image */
            image?: string | null;
        };
        /** TableSchema */
        TableSchema: {
            /** Id */
            id?: number;
            /** Table Number */
            table_number: number;
            /**
             * Qr Code
             * @default
             */
            qr_code: string;
            /**
             * Is Occupied
             * @default false
             */
            is_occupied: boolean;
        };
        /** OrderItemSchema */
        OrderItemSchema: {
            /** Id */
            id?: number;
            /** Menu Item Id */
            menu_item_id: number;
            /** Menu Item Name */
            menu_item_name?: string | null;
            /** Quantity */
            quantity: number;
            /** Price At Order */
            price_at_order: number;
            /**
             * Special Instructions
             * @default
             */
            special_instructions: string;
        };
        /** OrderSchema */
        OrderSchema: {
            /** Id */
            id?: number;
            /** Table Id */
            table_id?: number;
            /** Table Number */
            table_number?: number;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Special Instructions
             * @default
             */
            special_instructions: string;
            /** Payment Method */
            payment_method?: string | null;
            /**
             * Payment Status
             * @default false
             */
            payment_status: boolean;
            /**
             * Total Amount
             * @default 0
             */
            total_amount: number;
            /** Username */
            username?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["OrderItemSchema"][];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** CreateOrderSchema */
        CreateOrderSchema: {
            /** Table Id */
            table_id: number;
            /**
             * Special Instructions
             * @default
             */
            special_instructions: string;
            /** Payment Method */
            payment_method: string;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
        };
        /** UpdateOrderStatusSchema */
        UpdateOrderStatusSchema: {
            /** Status */
            status: string;
        };
        /** KitchenLoginSchema */
        KitchenLoginSchema: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** CartSyncResponseSchema */
        CartSyncResponseSchema: {
            /** Success */
            success: boolean;
        };
        /** CartDataSchema */
        CartDataSchema: {
            /** Items */
            items: components["schemas"]["CartItemSchema"][];
            /** Last Updated */
            last_updated: number;
        };
        /** CartItemSchema */
        CartItemSchema: {
            /** Menu Item Id */
            menu_item_id: number;
            menu_item: components["schemas"]["MenuItemSchema"];
            /** Quantity */
            quantity: number;
        };
        /** CartSyncRequestSchema */
        CartSyncRequestSchema: {
            /** User Id */
            user_id: number;
            cart: components["schemas"]["CartDataSchema"];
        };
        /** CartGetResponseSchema */
        CartGetResponseSchema: {
            cart?: components["schemas"]["CartDataSchema"] | null;
        };
        /** CheckoutStatusSchema */
        CheckoutStatusSchema: {
            /** Is Checkout In Progress */
            is_checkout_in_progress: boolean;
            /** Checkout By User Id */
            checkout_by_user_id?: number | null;
            /** Device Id */
            device_id?: string | null;
        };
        /** StartCheckoutSchema */
        StartCheckoutSchema: {
            /** User Id */
            user_id: number;
        };
        /** CreateOrderFromCartSchema */
        CreateOrderFromCartSchema: {
            /** User Id */
            user_id: number;
            /** Table Number */
            table_number: number;
            /** Payment Method */
            payment_method: string;
            /**
             * Special Instructions
             * @default
             */
            special_instructions: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    kitchenapi_views_check_user_exists: {
        parameters: {
            query: {
                username: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserExistsSchema"];
                };
            };
        };
    };
    kitchenapi_views_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_list_menu_items: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemSchema"][];
                };
            };
        };
    };
    kitchenapi_views_create_menu_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuItemSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_get_menu_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemSchema"];
                };
            };
        };
    };
    kitchenapi_views_update_menu_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuItemSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_delete_menu_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_list_tables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableSchema"][];
                };
            };
        };
    };
    kitchenapi_views_get_table: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableSchema"];
                };
            };
        };
    };
    kitchenapi_views_list_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"][];
                };
            };
        };
    };
    kitchenapi_views_create_order: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
        };
    };
    kitchenapi_views_get_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_update_order_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_kitchen_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KitchenLoginSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_get_kitchen_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"][];
                };
            };
        };
    };
    kitchenapi_views_update_order_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    kitchenapi_views_kitchen_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"][];
                };
            };
        };
    };
    kitchenapi_views_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    kitchenapi_views_get_cart: {
        parameters: {
            query: {
                user_id: number;
                last_updated?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartGetResponseSchema"];
                };
            };
        };
    };
    kitchenapi_views_sync_cart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartSyncRequestSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartSyncResponseSchema"];
                };
            };
        };
    };
    kitchenapi_views_start_checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartCheckoutSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutStatusSchema"];
                };
            };
        };
    };
    kitchenapi_views_get_checkout_status: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutStatusSchema"];
                };
            };
        };
    };
    kitchenapi_views_checkout_heartbeat: {
        parameters: {
            query: {
                user_id: number;
                device_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutStatusSchema"];
                };
            };
        };
    };
    kitchenapi_views_cancel_checkout: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutStatusSchema"];
                };
            };
        };
    };
    kitchenapi_views_complete_checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderFromCartSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
}
