# Generated by Django 6.0.1 on 2026-01-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="qr_code",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Pay in Cash"),
                    ("upi", "UPI Payment"),
                    ("card", "Card Payment"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
